In [79]:
import os
import json
import pandas as pd

In [80]:
print(os.getcwd())

c:\work\w\medical1\cbot


In [81]:
directory_path = './치료' 
json_data_list = []

# 디렉토리 내의 모든 파일을 검색
for filename in os.listdir(directory_path):
    if filename.endswith(".json"):
        file_path = os.path.join(directory_path, filename)

        # JSON 파일 열기
        with open(file_path, 'r', encoding='utf-8') as json_file:
            json_data = json.load(json_file)
            json_data_list.append(json_data)

# print(json_data_list)
# print(json_data_list[0]['question'])
json_data_list

[{'fileName': 'HC-Q-1124657',
  'participantsInfo': {'participantID': 'QC298',
   'gender': '여성',
   'age': '20대',
   'occupation': '사무직',
   'history': False,
   'rPlace': '서울/경기/인천'},
  'disease_category': '감염성질환',
  'disease_name': {'kor': '결핵', 'eng': 'Tuberculosis'},
  'intention': '치료',
  'question': '폐결핵을 치료하는 데에는 어떤 치료 옵션이 효과적일까요?',
  'entities': [{'id': 0, 'text': '결핵', 'entity': '질환명', 'position': 1}],
  'num_of_words': 7},
 {'fileName': 'HC-Q-1124658',
  'participantsInfo': {'participantID': 'QC060',
   'gender': '여성',
   'age': '50대 이상',
   'occupation': '교직',
   'history': False,
   'rPlace': '부산/대구/울산/경상'},
  'disease_category': '감염성질환',
  'disease_name': {'kor': '결핵', 'eng': 'Tuberculosis'},
  'intention': '치료',
  'question': '결핵 치료를 위해 필요한 치료 기간은 어느 정도인가요? 어떤 방법으로 치료해야 할까요?',
  'entities': [{'id': 0, 'text': '결핵', 'entity': '질환명', 'position': 0}],
  'num_of_words': 12},
 {'fileName': 'HC-Q-1124659',
  'participantsInfo': {'participantID': 'QC177',
   'gender': '남성',
   

In [85]:
json_data['question']

'결핵 환자의 치료 후 회복 기간은 얼마나 걸리는지 알려주세요.'

In [96]:
df= pd.DataFrame(json_data_list, columns=['question'])     # 파일 리스트 -> 데이터 프레임화 
# df=df.astype('string')                                    # df type string 으로 변경 
df

question
0                     폐결핵을 치료하는 데에는 어떤 치료 옵션이 효과적일까요?
1    결핵 치료를 위해 필요한 치료 기간은 어느 정도인가요? 어떤 방법으로 치료해야 할까요?
2                        폐결핵 치료를 위해 수술이 필요한 경우가 있는지요?
3                       폐결핵 치료에 사용되는 다양한 치료법들을 알려주세요.
4              임파선 결절에 생긴 멍울이 치료를 받을 때 주의해야 할 점이 있나요?
..                                                ...
839                  결핵 치료에 있어서 어떤 방식의 치료가 가장 효과적일까요?
840           잠복 결핵으로 인한 증상이 없는 경우에도 치료를 받을 필요가 있을까요?
841                     폐결핵 치료를 위한 최신 치료법이 있는지 알려주세요.
842                           폐결핵 치료에는 자연 요법이 효과적일까요?
843                결핵 환자의 치료 후 회복 기간은 얼마나 걸리는지 알려주세요.

[844 rows x 1 columns]

In [97]:
from konlpy.tag import *
from torchtext import data 
import json

import pandas as pd

tokenizer = Okt()
stopwords = ['의','가','에','들','는','잘','걍','과','도','를','으로','한','하다','!','?','<','>','(',')','[',']','|','#','.']

# 텍스트 전처리 함수
def norm_morphs(x):
    x = tokenizer.normalize(x) # 텍스트 Normalization
    x = tokenizer.morphs(x) # 형태소 분리
    x = [word for word in x if not word in stopwords] #불용어 처리
    return x

c:\Users\KOREAVC\anaconda3\Lib\site-packages\torchtext\data\__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)


In [83]:
json_data_list[0]['question']

'폐결핵을 치료하는 데에는 어떤 치료 옵션이 효과적일까요?'

In [98]:
#형태소 분석기 설치
!pip install konlpy

In [99]:
# 도구 임포트
import pandas as pd
import matplotlib.pyplot as plt
import urllib.request
from gensim.models.word2vec import Word2Vec
from konlpy.tag import Okt
from tqdm import tqdm # 현재 for문이 얼마나 실행되었는지를 알려주는 라이브러리

In [ ]:
okt=Okt()
tokenized_data = []
for sentence in tqdm(pd_data['question']):
    tokenized_sentence = okt.morphs(sentence, stem=True) # 토큰화
    stopwords_removed_sentence = [word for word in tokenized_sentence if not word in stopwords] # 불용어 제거
    tokenized_data.append(stopwords_removed_sentence)

print(tokenized_sentence)

특정 폴더 하위의 모든 JSON 파일 읽기
출처: https://devjss.com/python-read-multiple-json/#google_vignette

In [6]:
json_file_list = [file for file in file_list if file.endswith('.json')]

In [4]:
# 파일경로가 존재하는지 
os.path.isfile('치료/HC-Q-1124657.json')

True

In [8]:
for i in range(len(target_path_list)):
    files = os.listdir()

In [ ]:
purpose=[]
for i in range(len(target_path_list)):
    files = os.listdir(target_path+target_path_list[i])
    for k in range(len(files)):
        final_path = str(target_path)+str(target_path_list[i])+"/"+str(files[k])
        try:
            target_file = open(f"{final_path}", encoding="UTF-8")
            target_file = json.loads(target_file.read())
            for j in range(len(target_file['intention'][0]['annotations']['lines'])):
                purpose.append(target_file)
        except:
            print(f"error! {final_path}")

In [12]:
from pprint import pprint 
with open('치료/HC-Q-1124657.json') as f:
    data = json.load(f) 
    
pprint(data)

UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 113: illegal multibyte sequence

In [11]:
data['question']

'폐결핵을 치료하는 데에는 어떤 치료 옵션이 효과적일까요?'

In [12]:
from konlpy.tag import Kkma
import pickle

In [13]:
kkma=Kkma()
text= data['question']
# 형태소 추출
morphs = kkma.morphs(text) # text 변수에 저장된 문장을 형태소 단위로 토크나이징 합니다. 
print(morphs) 

['폐결핵', '을', '치료', '하', '는', '데', '에', '는', '어떤', '치료', '옵션', '이', '효과적', '이', 'ㄹ까요', '?']


In [14]:
# 형태소와 품사 태그 추출
pos = kkma.pos(text) # text 변수에 저장된 문장을 품사 태깅 합니다. 
print(pos) 

[('폐결핵', 'NNG'), ('을', 'JKO'), ('치료', 'NNG'), ('하', 'XSV'), ('는', 'ETD'), ('데', 'NNB'), ('에', 'JKM'), ('는', 'JX'), ('어떤', 'MDT'), ('치료', 'NNG'), ('옵션', 'NNG'), ('이', 'JKS'), ('효과적', 'NNG'), ('이', 'VCP'), ('ㄹ까요', 'EFQ'), ('?', 'SF')]


In [15]:
# 명사만 추출
nouns = kkma.nouns(text) # text 변수에 저장된 문장에서 품사가 명사인 단어들만 추출합니다. 
print(nouns) 

['폐결핵', '치료', '데', '옵션', '효과적']


In [16]:
# 문장 분리
sentences = "오늘 날씨는 어때요? 내일은 덥다던데." 
s = kkma.sentences(sentences) # 복합 문장이 있을 대 문장 단위로 토크나이징 합니다. 
print(s) 

['오늘 날씨는 어 때요?', '내일은 덥다 던데.']


In [17]:
# Okt 형태소 분석기 객체 생성
from konlpy.tag import Okt

okt=Okt()
text= data['question']
okt_morphs=okt.morphs(text)

print(okt_morphs)

['폐결핵', '을', '치료', '하는', '데', '에는', '어떤', '치료', '옵션', '이', '효과', '적', '일까', '요', '?']


In [18]:
okt_pos=okt.pos(text)
print(okt_pos)

# 명사만 추출
okt_noun=okt.nouns(text)
print(okt_noun)

[('폐결핵', 'Noun'), ('을', 'Josa'), ('치료', 'Noun'), ('하는', 'Verb'), ('데', 'Noun'), ('에는', 'Josa'), ('어떤', 'Adjective'), ('치료', 'Noun'), ('옵션', 'Noun'), ('이', 'Josa'), ('효과', 'Noun'), ('적', 'Suffix'), ('일까', 'Verb'), ('요', 'Noun'), ('?', 'Punctuation')]
['폐결핵', '치료', '데', '치료', '옵션', '효과', '요']


Okt는 앞서 소개한 형태소 분석기보다 분석되는 품사 정보는 작지만 분석 속도는 제일 빠릅니다. 또한 normalize() 함수를 지원해 오타가 섞인 문장을 정규화해서 처리하기 효율적입니다.

In [19]:
text= data['question']
print(okt.normalize(text))
print(okt.phrases(text))

폐결핵을 치료하는 데에는 어떤 치료 옵션이 효과적일까요?
['폐결핵', '치료', '치료하는 데', '어떤 치료', '어떤 치료 옵션', '옵션']


In [20]:
from konlpy.tag import Komoran

# 코모란 형태소 분석기 객체 생성
komoran=Komoran()
text= data['question']
morphs=komoran.morphs(text)
print(morphs)

#형태소와 품사 태그 추출
pos=komoran.pos(text)
print(pos)

#명사만 추출
noun=komoran.nouns(text)
print(noun)

['폐결핵', '을', '치료', '하', '는', '데', '에', '는', '어떤', '치료', '옵션', '이', '효과', '적', '이', 'ㄹ까요', '?']
[('폐결핵', 'NNG'), ('을', 'JKO'), ('치료', 'NNG'), ('하', 'XSV'), ('는', 'ETM'), ('데', 'NNB'), ('에', 'JKB'), ('는', 'JX'), ('어떤', 'MM'), ('치료', 'NNG'), ('옵션', 'NNP'), ('이', 'JKS'), ('효과', 'NNG'), ('적', 'XSN'), ('이', 'VCP'), ('ㄹ까요', 'EF'), ('?', 'SF')]
['폐결핵', '치료', '데', '치료', '옵션', '효과']


#단어임베딩
-원핫인코딩
-분산 표현 형태의 신경망 기반 단어 임베딩의 대표적인 방법인 Word2Vec

In [21]:
import numpy as np

komoran = Komoran()
text= data['question']

# 문장에서 명사만 추출
nouns = komoran.nouns(text) 

# 단어 사전 구축 및 단어별 인덱스 부여
dics = {}
for word in nouns:
  if word not in dics.keys(): # 이미 저장된 단어는 다시 저장하지 않음
    dics[word] = len(dics) # key가 단어, value가 인덱스
print("명사 갯수: ",len(dics))

# 원-핫 벡터 차원의 크기는 단어 사전의 크기
nb_classes = len(dics)

# 단어별 인덱스값을 리스트로 변환
targets = list(dics.values())

# 원-핫 벡터 생성
one_hot_targets = np.eye(nb_classes) # nb_classes 크기대로 단위행렬을 반환
one_hot_targets = one_hot_targets[targets] # 단위행렬을 단어 사전의 순서에 맞게 정렬
print(one_hot_targets)

명사 갯수:  5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


출처: https://simon-yoon.tistory.com/143 [Simon Yoon's blog:티스토리]

In [23]:
import pandas as pd

In [24]:
import pandas as pd
import json

# opening JSON file
f = open('./치료/HC-Q-1124657.json')
data = json.load(f)
df['disease_category',]

NameError: name 'df' is not defined

In [25]:
from konlpy.tag import *
from torchtext import data 
import json

import pandas as pd

tokenizer = Okt()
stopwords = ['의','가','에','들','는','잘','걍','과','도','를','으로','한','하다','!','?','<','>','(',')','[',']','|','#','.']

# 텍스트 전처리 함수
def norm_morphs(x):
    x = tokenizer.normalize(x) # 텍스트 Normalization
    x = tokenizer.morphs(x) # 형태소 분리
    x = [word for word in x if not word in stopwords] #불용어 처리
    return x

c:\Users\KOREAVC\anaconda3\Lib\site-packages\torchtext\data\__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)


In [26]:
# KR-SBERT 설치
!pip install -U sentence-transformers

     ---------------------------------------- 0.0/43.7 kB ? eta -:--:--
     --------- ------------------------------ 10.2/43.7 kB ? eta -:--:--
     -------------------------------------- 43.7/43.7 kB 711.0 kB/s eta 0:00:00
   ---------------------------------------- 0.0/227.1 kB ? eta -:--:--
   ---------------------------------------- 227.1/227.1 kB 7.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/417.2 kB ? eta -:--:--
   --------------------------------------  409.6/417.2 kB 12.9 MB/s eta 0:00:01
   ---------------------------------------- 417.2/417.2 kB 8.7 MB/s eta 0:00:00
   ---------------------------------------- 0.0/9.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/9.4 MB 14.2 MB/s eta 0:00:01
   ---- ----------------------------------- 1.0/9.4 MB 12.3 MB/s eta 0:00:01
   ------ --------------------------------- 1.5/9.4 MB 13.3 MB/s eta 0:00:01
   -------- ------------------------------- 2.0/9.4 MB 12.9 MB/s eta 0:00:01
   ---------- --

In [27]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()

import torch
from sentence_transformers import SentenceTransformer

c:\Users\KOREAVC\anaconda3\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


RuntimeError: Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.

In [ ]:
model = SentenceTransformer('snunlp/KR-SBERT-V40K-klueNLI-augSTS')

data['embedding_vector'] = data['input'].progress_map(lambda x : model.encode(x))
data.to_excel("data_embedding.xlsx", index=False)
embedding_data = torch.tensor(data['embedding_vector'].tolist())
torch.save(embedding_data, 'embedding_data.pt')

In [51]:
from gensim.models import Word2Vec
from konlpy.tag import Komoran
import time

In [ ]:
class Preprocess:
    def __init__(self, word2index_dic='../train_tools/dict/chatbot_dict.bin' ,userdic='user_dic.tsv'): # userdic 인자에는 사용자 정의 사전 파일 경로 입력가능
        # 단어 인덱스 사전 불러오기
        if(word2index_dic != ''):
            f = open(word2index_dic, "rb")
            self.word_index = pickle.load(f)
            f.close()
            print("단어 사전 로드 완료..")
        else:
            self.word_index = None
            print("단어 사전 로드 실패..")

        # 형태소 분석기 초기화
        self.komoran = Komoran(userdic=userdic)

        # 제외할 품사
        # 참조 : https://docs.komoran.kr/firststep/postypes.html
        # 관계언 제거, 기호 제거
        # 어미 제거
        # 접미사 제거
        self.exclusion_tags = [
            'JKS', 'JKC', 'JKG', 'JKO', 'JKB', 'JKV', 'JKQ',
            # 주격조사, 보격조사, 관형격조사, 목적격조사, 부사격조사, 호격조사, 인용격조사
            'JX', 'JC',
            # 보조사, 접속조사
            'SF', 'SP', 'SS', 'SE', 'SO',
            # 마침표,물음표,느낌표(SF), 쉼표,가운뎃점,콜론,빗금(SP), 따옴표,괄호표,줄표(SS), 줄임표(SE), 붙임표(물결,숨김,빠짐)(SO)
            'EP', 'EF', 'EC', 'ETN', 'ETM',
            # 선어말어미, 종결어미, 연결어미, 명사형전성어미, 관형형전성어미
            'XSN', 'XSV', 'XSA'
            # 명사파생접미사, 동사파생접미사, 형용사파생접미사
        ]


    # 형태소 분석기 POS 태거
    def pos(self, sentence):
        return self.komoran.pos(sentence)

    # 불용어 제거 후 필요한 품사 정보만 가져오기
    def get_keywords(self, pos, without_tag=False):
        f = lambda x: x in self.exclusion_tags
        word_list = []
        for p in pos:
            if f(p[1]) is False:
                word_list.append(p if without_tag is False else p[0])
        return word_list

    # 키워드를 단어 인덱스 시퀀스로 변환
    def get_wordidx_sequence(self, keywords):
        if self.word_index is None:
            return []
        w2i = []
        for word in keywords:
            try:
                w2i.append(self.word_index[word])
            except KeyError:
                # 해당 단어가 사전에 없는 경우 OOV 처리
                w2i.append(self.word_index['OOV'])
        return w2i


In [125]:
# path = './1.질문/호흡기질환/천식/검진' 
path='./1.질문/호흡기질환/천식/검진'
#[path] 에 데이터가 있는 디렉터리

file_list = os.listdir(path)
# 경로 내에 파일을 모두 불러옴

json_file_list = [file for file in file_list if file.endswith('.json')]
#json 확장자를 가진 파일로 새로운 리스트 생성

In [127]:
len(file_list)

388

In [149]:
data['question']

'천식을 검진받기 전에 어떤 예방 조치를 취해야 하는지 자세한 설명을 해주세요. 검진 후에는 어떤 예방 조치를 취해야 할까요?'

In [148]:
data['disease_category']

'호흡기질환'

In [ ]:



class Preprocess:
    def __init__(self, word2index_dic='../train_tools/dict/chatbot_dict.bin' ,userdic='user_dic.tsv'): # userdic 인자에는 사용자 정의 사전 파일 경로 입력가능
        # 단어 인덱스 사전 불러오기
        if(word2index_dic != ''):
            f = open(word2index_dic, "rb")
            self.word_index = pickle.load(f)
            f.close()
            print("단어 사전 로드 완료..")
        else:
            self.word_index = None
            print("단어 사전 로드 실패..")

        # 형태소 분석기 초기화
        self.komoran = Komoran(userdic=userdic)

        # 제외할 품사
        # 참조 : https://docs.komoran.kr/firststep/postypes.html
        # 관계언 제거, 기호 제거
        # 어미 제거
        # 접미사 제거
        self.exclusion_tags = [
            'JKS', 'JKC', 'JKG', 'JKO', 'JKB', 'JKV', 'JKQ',
            # 주격조사, 보격조사, 관형격조사, 목적격조사, 부사격조사, 호격조사, 인용격조사
            'JX', 'JC',
            # 보조사, 접속조사
            'SF', 'SP', 'SS', 'SE', 'SO',
            # 마침표,물음표,느낌표(SF), 쉼표,가운뎃점,콜론,빗금(SP), 따옴표,괄호표,줄표(SS), 줄임표(SE), 붙임표(물결,숨김,빠짐)(SO)
            'EP', 'EF', 'EC', 'ETN', 'ETM',
            # 선어말어미, 종결어미, 연결어미, 명사형전성어미, 관형형전성어미
            'XSN', 'XSV', 'XSA'
            # 명사파생접미사, 동사파생접미사, 형용사파생접미사
        ]


    # 형태소 분석기 POS 태거
    def pos(self, sentence):
        return self.komoran.pos(sentence)

    # 불용어 제거 후 필요한 품사 정보만 가져오기
    def get_keywords(self, pos, without_tag=False):
        f = lambda x: x in self.exclusion_tags
        word_list = []
        for p in pos:
            if f(p[1]) is False:
                word_list.append(p if without_tag is False else p[0])
        return word_list

    # 키워드를 단어 인덱스 시퀀스로 변환
    def get_wordidx_sequence(self, keywords):
        if self.word_index is None:
            return []
        w2i = []
        for word in keywords:
            try:
                w2i.append(self.word_index[word])
            except KeyError:
                # 해당 단어가 사전에 없는 경우 OOV 처리
                w2i.append(self.word_index['OOV'])
        return w2i


In [82]:
# path = './1.질문/호흡기질환/천식/검진' 
path='./1.질문/호흡기질환/천식/검진'
#[path] 에 데이터가 있는 디렉터리

file_list = os.listdir(path)
# 경로 내에 파일을 모두 불러옴

json_file_list = [file for file in file_list if file.endswith('.json')]
#json 확장자를 가진 파일로 새로운 리스트 생성

In [89]:
len(file_list)
file_list[:3]

['HC-Q-0016805.json', 'HC-Q-0016806.json', 'HC-Q-0016807.json']

In [90]:
json_file_list[:3]

['HC-Q-0016805.json', 'HC-Q-0016806.json', 'HC-Q-0016807.json']

In [93]:
len(file_list)

388

In [78]:
corpus_name = "question_corpus"
corpus = os.path.join("data", corpus_name)

In [79]:
def printLines(file, n=10):
    with open(file, 'rb') as datafile:
        lines = datafile.readlines()
    for line in lines[:n]:
        print(line)

printLines(os.path.join(corpus, "utterances.jsonl"))

FileNotFoundError: [Errno 2] No such file or directory: 'data\\question_corpus\\utterances.jsonl'

In [75]:

f=open('./1.질문/호흡기질환/천식/검진/HC-Q-0016805.json') 
data = json.load(f)
df= pd.json_normalize(data,record_path=['question'])

TypeError: {'fileName': 'HC-Q-0016805', 'participantsInfo': {'participantID': 'QC192', 'gender': '여성', 'age': '50대 이상', 'occupation': '주부', 'history': False, 'rPlace': '부산/대구/울산/경상'}, 'disease_category': '호흡기질환', 'disease_name': {'kor': '천식', 'eng': 'Asthma'}, 'intention': '검진', 'question': '천식을 검진받기 전에 어떤 예방 조치를 취해야 하는지 자세한 설명을 해주세요. 검진 후에는 어떤 예방 조치를 취해야 할까요?', 'entities': [{'id': 0, 'text': '천식', 'entity': '질환명', 'position': 0}], 'num_of_words': 18} has non list value 천식을 검진받기 전에 어떤 예방 조치를 취해야 하는지 자세한 설명을 해주세요. 검진 후에는 어떤 예방 조치를 취해야 할까요? for path question. Must be list or null.

In [48]:
with open('test.json') as f:
    js = json.loads(f.read()) ## json 라이브러리 이용
df = pd.DataFrame(js)
df = pd.read_json('test.json') ## pd.read_json 이용
df = pd.DataFrame(data)
df = pd.read_json('HC-Q-0016805.json') ## pd.read_json 이용

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [47]:
DataFrame = []
for json in json_file_list:
	DataFrame.append(json.load(f))


In [29]:
def counting(path):
    cnt = 0
    data_dir = path

    for path in os.listdir(data_dir):
        if os.path.isfile(os.path.join(data_dir, path)):
            cnt += 1

    print(f'데이터 개수 = {cnt}')
    return cnt

In [26]:
target_path = "1.질문/근골격질환/관절염/검진/HC-Q-0497474.json"

In [31]:
question= open(f'1.질문/호흡기질환/천식/검진/HC-Q-0016805.json', encoding="UTF-8")
question= json.loads(question.read())

In [ ]:
purpose = []
for i in range(len(target_path_list)):
    files = os.listdir(target_path+target_path_list[i])
    for k in range(len(files)):
        final_path = str(target_path)+str(target_path_list[i])+"/"+str(files[k])
        try:
            target_file = open(f"{final_path}", encoding="UTF-8")
            target_file = json.loads(target_file.read())
            for j in range(len(target_file['info'][0]['annotations']['lines'])):
                purpose.append(target_file['info'][0]['annotations']['lines'][j]['norm_text'][2:])
        except:
            print(f"error! {final_path}")

In [25]:
target_path_list = os.listdir(target_path)

FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: '1.질문/근골격질환/관절염/검진/HC-Q-0497474.json'

In [32]:

total_data = 0
for i in range(len(target_path_list)):
    cnt = counting(target_path+target_path_list[i])
    total_data += cnt
print(f'총 데이터 개수 = {total_data}')

NameError: name 'target_path_list' is not defined