#500개 단어 ->1000개 
#길이 100 ->200 변경해서 테스트

In [1]:
from tensorflow import keras
from tensorflow.keras.datasets import imdb
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family']='Malgun Gothic'
matplotlib.rcParams['font.size']=10
matplotlib.rcParams['axes.unicode_minus'] = False

In [2]:
(train_input,train_target),(test_input,test_target)=keras.datasets.imdb.load_data(
    num_word=1000
)

In [3]:
print(train_input.shape,test_input.shape)

(25000,) (25000,)


In [4]:
print(train_target[:20])

[1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 1]


In [3]:
from sklearn.model_selection import train_test_split
train_input,val_input,train_target,val_target=train_test_split(
    train_input,train_target,test_size=0.2,random_state=42
)

In [6]:
print(train_input.shape,val_input.shape)

(20000,) (5000,)


In [7]:
len(train_input[0])

259

In [4]:
lengths=np.array([len(x) for x in train_input])
lengths

array([259, 520, 290, ..., 300,  70,  77])

In [9]:
np.max(lengths)

1854

In [5]:
#시퀀스 패딩
from tensorflow.keras.preprocessing.sequence import pad_sequences
train_seq = pad_sequences(train_input,maxlen=100)

In [11]:
print(train_input[0][-10:])

[6, 1968, 46, 7, 14, 20, 10, 10, 470, 158]


In [12]:
train_seq.shape

(20000, 100)

In [13]:
print(train_seq[5])

[    0     0     0     0     1   542   195    19    49  3005  2656   190
     4  2409   352 32541   183    10    10    13    82    79     4  1384
    36    71   269     8  1465    25    19    49     7     4  2177  9752
 34466  3910   538    10    10    48    25    40  2158    11   843   538
    40 14062   543     5     4  3253   568    95    14   238    56   129
   890    10    10    21   691    94   364   352  2661  2208    11   190
    24   484  4170     7    94   205   405    10    10    87   816    34
    49 12916     7 25790  4175  1208 25790  4753   290  3303    46    48
    64    18     4   816]


In [6]:
val_seq=pad_sequences(val_input,maxlen=100)
val_seq

array([[   32,   934,   225, ...,    14,    58, 88223],
       [   53,  6005,     8, ...,     7,    32,  2088],
       [    0,     0,     0, ...,   737,    33,    32],
       ...,
       [  383,   740,   120, ...,    16,    99,    76],
       [  106,   345,    12, ...,   120,  1539,   156],
       [    4,   114,    21, ...,     4,   568,  1255]])

In [7]:
model=keras.Sequential()
model.add(keras.layers.SimpleRNN(8,input_shape=(100,500)))
model.add(keras.layers.Dense(1,activation='sigmoid'))

c:\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [16]:
train_seq.shape

(20000, 100)

In [8]:
train_oh=keras.utils.to_categorical(train_seq)

MemoryError: Unable to allocate 1.29 TiB for an array with shape (2000000, 88587) and data type float64