In [17]:
# from sklearn import svm,metrics
# from sklearn.neighbors import KNeighborsClassifier  #분류
# from sklearn.neighbors import KNeighborsRegressor  #예측
from sklearn.linear_model import LinearRegression  #선형회귀
from sklearn.preprocessing import PolynomialFeatures  #다항특성을 만들어주는 라이브러리

from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import random
matplotlib.rcParams['font.family']='Malgun Gothic'  #한글설정
matplotlib.rcParams['font.size']= '10'  #글자크기
matplotlib.rcParams['axes.unicode_minus'] = False

In [4]:
import pandas as pd
df=pd.read_csv('http://bit.ly/fish_csv')
df.head(3)

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961

In [8]:
# 데이터 확인: nan,0,타입,최소값,최대값, 값이 분포, 각 특성별 데이터 최대값

#1. 데이터 전처리 - data, target 분리
fish_input=df.iloc[:,1:].to_numpy()
fish_target=df['Species'].to_numpy()
#train,test 셋트 분리
train_input,test_input,train_target,test_target = train_test_split(
    fish_input,fish_target,random_state=42
)

# 표준화 작업
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

#2. 데이터 훈련시키기
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(train_scaled,train_target)

#3. 데이터 예측
predict=lr.predict(test_scaled[:5])
print(predict)
#4. 데이터 정답률 -train, test
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

#####과소적합(random_state=42 빼고 돌려보기.)

['Perch' 'Smelt' 'Pike' 'Perch' 'Perch']
0.8067226890756303
0.85


In [12]:
lr.predict(train_scaled[:5])

array(['Bream', 'Pike', 'Smelt', 'Perch', 'Parkki'], dtype=object)

In [13]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [11]:
#predict:분류한 값을 출력
#predict_proba:각 특성별로 분류 퍼센트를 출력

proba = lr.predict_proba(train_scaled[:5])
np.round(proba,decimals=3)

array([[0.954, 0.01 , 0.012, 0.002, 0.004, 0.   , 0.017],
       [0.002, 0.   , 0.044, 0.941, 0.008, 0.   , 0.004],
       [0.   , 0.046, 0.105, 0.001, 0.061, 0.786, 0.001],
       [0.004, 0.029, 0.671, 0.013, 0.258, 0.012, 0.014],
       [0.074, 0.384, 0.209, 0.01 , 0.287, 0.016, 0.021]])

In [14]:
decision=lr.decision_function(test_scaled[:5])
print(np.round(decision,decimals=2))

[[-2.35  0.75  2.54 -1.67  1.87  0.35 -1.49]
 [-4.17  1.38  2.1  -1.99  1.73  3.85 -2.9 ]
 [-1.45 -1.48  1.73  2.67  1.46 -1.83 -1.09]
 [ 0.02  0.26  2.18 -0.52  1.46 -3.   -0.39]
 [-2.22 -0.27  2.84 -0.4   1.84 -0.74 -1.06]]


In [6]:
df.describe()

Weight      Length    Diagonal      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   28.415723   31.227044    8.970994    4.417486
std     357.978317   10.716328   11.610246    4.286208    1.685804
min       0.000000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   63.400000   68.000000   18.957000    8.142000

In [19]:
decisions =lr.decision_function(train_scaled[:5])
print(np.round(decision,decimals=2))

[[-2.35  0.75  2.54 -1.67  1.87  0.35 -1.49]
 [-4.17  1.38  2.1  -1.99  1.73  3.85 -2.9 ]
 [-1.45 -1.48  1.73  2.67  1.46 -1.83 -1.09]
 [ 0.02  0.26  2.18 -0.52  1.46 -3.   -0.39]
 [-2.22 -0.27  2.84 -0.4   1.84 -0.74 -1.06]]


In [22]:
from scipy.special import softmax
print(np.round(decision,decimals=2))
proba = softmax(decision,axis = 1)

[[-2.35  0.75  2.54 -1.67  1.87  0.35 -1.49]
 [-4.17  1.38  2.1  -1.99  1.73  3.85 -2.9 ]
 [-1.45 -1.48  1.73  2.67  1.46 -1.83 -1.09]
 [ 0.02  0.26  2.18 -0.52  1.46 -3.   -0.39]
 [-2.22 -0.27  2.84 -0.4   1.84 -0.74 -1.06]]


In [ ]:
# 결과값 도출 형태 분석#

In [23]:
predict = lr.predict(test_scaled[:5])
print(predict)

#기울기, y절편의 값을 적용시켜서 z 점수 출력


['Perch' 'Smelt' 'Pike' 'Perch' 'Perch']
